### ISSUE TITLE
Triplescreen rendering mode causes the camera to stay black

### ISSUE THREAD

**Issue by Plebstar** [ac-custom-shaders-patch/acc-obs-plugin#3]
Hello, unfortunately, when using the Triplescreen rendering mode in AC, the app wont capture any camera views, besides the three "Basic" ones (Clean, include HUD & Virtual mirror). 
I usually play with triplescreen, custom res 7680x1440, no fullscreen.
Enabling fullscreen and Nvidia Surround did not help. Only fix is to use singlescreen & fullscreen.
Is there anything specific that I should try? Or is it simply not supported yet?

Thanks in advance!

Edit: Has been fixed with the latest CSP update,

**Comment by turbasosimracing** [comment]
I have the same problem rendering in triple screen but works great in single screen
